swagger: '2.0'

info:
  version: "1.0.0"
  title: OAuth2 Client Registration
  description: OAuth2 Client Registration microservices endpoints. 
  contact:
    email: stevehu@gmail.com
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: oauth2.networknt.com
schemes:
  - http
  - https

consumes:
  - application/json
produces:
  - application/json

paths:
  /oauth2/client:
    post:
      description: Return a client object
      operationId: createClient
      parameters:
      - in: "body"
        name: "body"
        description: "Client object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Client"      
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Client"          
      security:
      - client_auth:
        - "oauth.client.w"
    put:
      description: Return the updated client
      operationId: updateClient
      parameters:
      - in: "body"
        name: "body"
        description: "Client object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Client"      
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Client"          
      security:
      - client_auth:
        - "oauth.client.w"
    get:
      description: Return all clients
      operationId: getAllClient
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Client"
      security:
      - client_auth:
        - "oauth.client.r"
          
  /oauth2/client/{clientId}:
    delete:
      description: Delete a client by Id
      operationId: deleteClient
      parameters:
      - name: "clientId"
        in: "path"
        description: "Client Id"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid clientId supplied"
        404:
          description: "Client not found"
      security:
        - client_auth:
          - oauth.client.w
    get:
      description: Get a client by Id
      operationId: getClient
      parameters:
      - name: "clientId"
        in: "path"
        description: "Client Id"
        required: true
        type: "string"
      responses:
        200: 
          description: Successful response
          schema:
            $ref: "#/definitions/Client"          
        400:
          description: "Invalid clientId supplied"
        404:
          description: "Client not found"
      security:
        - client_auth:
          - oauth.client.r
          - oauth.client.w

securityDefinitions:
  client_auth:
    type: "oauth2"
    authorizationUrl: "http://localhost:8888/oauth2/code"
    flow: "implicit"
    scopes:
      oauth.client.w: "write oauth client"
      oauth.client.r: "read oauth client"
definitions:
  Client:
    type: "object"
    required:
    - clientType
    - clientName
    - clientDesc
    - ownerId
    - scope
    properties:
      clientId:
        type: "string"
        description: "a unique client id"
      clientSecret:
        type: "string"
        description: "client secret"
      clientType:
        type: "string"
        description: "client type"
        enum:
        - server
        - mobile
        - service
        - standalone
        - browser
      clientName:
        type: "string"
        description: "client name"
      clientDesc:
        type: "string"
        description: "client description"
      ownerId:
        type: "string"
        description: "client owner id"
      scope:
        type: "string"
        description: "client scope separated by space"
      redirectUrl:
        type: "string"
        description: "redirect url"
      createDt:
        type: "string"
        format: "date-time"
        description: "create date time"
      updateDt:
        type: "string"
        format: "date-time"
        description: "update date time"
